name: Docker Compose CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag Docker images
        run: |
          docker compose -f docker-compose.yml build

      - name: Tag & Push Backend image
        run: |
          docker tag kusa-kusa-backend:latest taamtera/kusa-backend:latest
          docker push taamtera/kusa-backend:latest

      - name: Tag & Push Frontend image
        run: |
          docker tag kusa-kusa-frontend:latest taamtera/kusa-frontend:latest
          docker push taamtera/kusa-frontend:latest